[package]
name = "leaf-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
automerge = "0.6.1"
beelay-core = { git = "https://github.com/inkandswitch/keyhive.git", version = "0.1.0" }
blake3 = "1.8.2"
blocking = "1.6.1"
ed25519-dalek = "2.1.1"
fjall = "2.11.0"
loro = "1.5.9"
rand = "0.8.0"
smallvec = "1.15.1"
smol = "2.0.2"
